### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by timgroothuis** [NotARobot6969/PwnedPhysics#4]
i was able to run npm install without any problems but when i run npm start in cmd i get this error:

```
C:\Users\TimAn\Downloads\PwnedPhysics-main\PwnedPhysics-main>npm start

> pwnedphysics@1.0.0 start
> node app.js

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (node:net:1724:21)
    at listenInCluster (node:net:1789:12)
    at Server.listen (node:net:1877:7)
    at Function.listen (C:\Users\TimAn\Downloads\PwnedPhysics-main\PwnedPhysics-main\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\TimAn\Downloads\PwnedPhysics-main\PwnedPhysics-main\app.js:33:5)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1768:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 4567
}

Node.js v19.4.0
```

**Comment by timgroothuis** [comment]
i fixed it for some reason port was excluded so i did 
```net stop winnat```
and
```net start winnat```
that seemed to fix the problem
